name = "earnings-cal-worker"
main = "src/worker/index.js"
compatibility_date = "2024-01-01"

# Custom domain routing on Cloudflare
routes = [
  { pattern = "earnings.ethanfun.xyz/api/*", zone_name = "ethanfun.xyz" },
  { pattern = "earnings.ethanfun.xyz/ics/s/*", zone_name = "ethanfun.xyz" }
]

# KV Namespace binding for subscriber analytics & token mapping
# Note: id will be populated after running kv namespace creation command
[[kv_namespaces]]
binding = "SUBSCRIBERS"
id = "3f83537ae23d4edba060a0bf33fa5ebc"
